#!/usr/bin/env python3
"""
Install (or remove) the pr-review pre-push git hook in the current repo.

The hook auto-generates a .snapshot file whenever you push a branch that has
a Claude Code session. Snapshots are written to .claude/snapshots/<branch>.snapshot
and gitignored by default.

Usage:
    python setup_hook.py           # install hook into .git/hooks/pre-push
    python setup_hook.py --remove  # remove the hook
    python setup_hook.py --status  # show current hook state
"""

import os
import stat
import sys
from pathlib import Path

HOOK_MARKER = "# pr-review-hook"


def find_git_root() -> Path | None:
    p = Path.cwd()
    while p != p.parent:
        if (p / ".git").is_dir():
            return p
        p = p.parent
    return None


def find_export_script() -> Path:
    """Return absolute path to export.py."""
    # Prefer a copy in the same directory as this script
    here = Path(__file__).resolve().parent
    candidate = here / "export.py"
    if candidate.exists():
        return candidate
    raise FileNotFoundError(f"export.py not found next to {__file__}")


def hook_script(export_script: Path, snapshots_dir: str) -> str:
    return f"""\
#!/usr/bin/env python3
{HOOK_MARKER}
# Auto-generated by setup_hook.py — do not edit manually.
# Re-run setup_hook.py to update.

import subprocess, sys, os
from pathlib import Path

EXPORT_SCRIPT = "{export_script}"
SNAPSHOTS_DIR = "{snapshots_dir}"

def main():
    pushed_branches = []
    for line in sys.stdin:
        parts = line.strip().split()
        if len(parts) < 2:
            continue
        local_ref = parts[0]
        if local_ref.startswith("refs/heads/"):
            pushed_branches.append(local_ref[len("refs/heads/"):])

    if not pushed_branches:
        sys.exit(0)

    Path(SNAPSHOTS_DIR).mkdir(parents=True, exist_ok=True)

    for branch in pushed_branches:
        safe = branch.replace("/", "-")
        out = str(Path(SNAPSHOTS_DIR) / f"{{safe}}.snapshot")
        print(f"\\n[pr-review] Generating snapshot for branch: {{branch}}")
        result = subprocess.run(
            [sys.executable, EXPORT_SCRIPT, "--output", out, "--quiet"],
            capture_output=False,
        )
        if result.returncode == 0:
            print(f"[pr-review] Snapshot: {{out}}")
            print(f"[pr-review] Attach this file to your PR so reviewers can load it.")
        else:
            # Never block the push — hook failures are informational only
            print(f"[pr-review] Warning: snapshot generation failed (push continues).")

    sys.exit(0)

main()
"""


def ensure_gitignore(git_root: Path, snapshots_rel: str) -> None:
    """Add snapshots dir to .gitignore if not already there."""
    gitignore = git_root / ".gitignore"
    pattern = f"{snapshots_rel}/"
    if gitignore.exists():
        if pattern in gitignore.read_text():
            return
        with open(gitignore, "a") as f:
            f.write(f"\n# pr-review snapshots (conversation history — keep local)\n{pattern}\n")
    else:
        gitignore.write_text(f"# pr-review snapshots (conversation history — keep local)\n{pattern}\n")
    print(f"Added {pattern} to .gitignore")


def install(git_root: Path) -> None:
    export_script = find_export_script()
    snapshots_dir = str(git_root / ".claude" / "snapshots")
    hook_path = git_root / ".git" / "hooks" / "pre-push"

    # Check if a non-pr-review hook already exists
    if hook_path.exists():
        existing = hook_path.read_text()
        if HOOK_MARKER not in existing:
            print(f"Warning: a pre-push hook already exists at {hook_path}")
            print("It was not written by pr-review. Overwrite? [y/N] ", end="")
            if input().strip().lower() != "y":
                print("Aborted.")
                sys.exit(1)

    hook_path.write_text(hook_script(export_script, snapshots_dir))
    hook_path.chmod(hook_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    print(f"Hook installed: {hook_path}")

    ensure_gitignore(git_root, ".claude/snapshots")

    print(f"\nDone. Next time you push, a snapshot will be written to:")
    print(f"  {snapshots_dir}/<branch>.snapshot")
    print(f"\nShare that file with your reviewer. They run:")
    print(f"  python load.py <branch>.snapshot")


def remove(git_root: Path) -> None:
    hook_path = git_root / ".git" / "hooks" / "pre-push"
    if not hook_path.exists():
        print("No pre-push hook found.")
        return
    if HOOK_MARKER not in hook_path.read_text():
        print("The existing pre-push hook was not installed by pr-review. Leaving it alone.")
        return
    hook_path.unlink()
    print(f"Hook removed: {hook_path}")


def status(git_root: Path) -> None:
    hook_path = git_root / ".git" / "hooks" / "pre-push"
    if not hook_path.exists():
        print("No pre-push hook installed.")
    elif HOOK_MARKER in hook_path.read_text():
        print(f"pr-review hook is installed: {hook_path}")
        snapshots = git_root / ".claude" / "snapshots"
        if snapshots.exists():
            snaps = list(snapshots.glob("*.snapshot"))
            print(f"Snapshots: {len(snaps)} in {snapshots}")
            for s in sorted(snaps):
                size_kb = s.stat().st_size // 1024
                print(f"  {s.name}  ({size_kb} KB)")
        else:
            print("No snapshots generated yet.")
    else:
        print("A pre-push hook exists but was not installed by pr-review.")


def main():
    args = sys.argv[1:]

    git_root = find_git_root()
    if not git_root:
        print("Error: not inside a git repository.")
        sys.exit(1)
    print(f"Repo: {git_root}")

    if "--remove" in args:
        remove(git_root)
    elif "--status" in args:
        status(git_root)
    else:
        install(git_root)


if __name__ == "__main__":
    main()
